### PR TITLE
ENH: adjust  output  arg description to mention that it is a prefix

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by satra** [comment]
@yarikoptic  - i'm going to close this, since this is not the cli for this application. it's `cli_click.py` - the general nobrainer cli should be updated as necessary in the main nobrainer repo. kwyk uses a former state of nobrainer.

**Comment by yarikoptic** [comment]
Ah ok... Just please check if current  --help corresponds to the reality ;-)

**Comment by satra** [comment]
current output

```
$ docker run -it --rm -v $(pwd):/data neuronets/kwyk:latest-cpu --help
Bayesian dropout functions have been loaded.
Usage: nobrainer_bwn [OPTIONS] INFILE OUTPREFIX

  Predict labels from features using a trained model.

  The predictions are saved to OUTPREFIX_* with the same extension as the
  input file.

  If you encounter out-of-memory issues, use a lower batch size value.

Options:
  -m, --model [bvwn_multi_prior|bwn_multi|bwn]
                                  Model to use for prediction.  [required]
  -n, --n-samples INTEGER         Number of samples to predict.
  -b, --batch-size INTEGER        Batch size during prediction.
  --save-variance                 Save volume with variance across `n-samples`
                                  predictions.
  --save-entropy                  Save volume of entropy values.
  --help                          Show this message and exit.
```

**Comment by satra** [comment]
i haven't released a new version yet. was waiting to see what comes of #3  first.

**Pull request closed without merging**
