### PR TITLE
add average uncertainty to cli #20

### PR DESCRIPTION
**Pull request by Hoda1394**
The cli calculates the average uncertainty of input and saves it as a json file. #20 #

### CODE REVIEW

**Comment by kaczmarj** [comment]
this looks good to me @Hoda1394

**Comment by Hoda1394** [comment]
@kaczmarj I just need to do some tests...will let you know and then it can be merged.

**Comment by Hoda1394** [comment]
Docker build fails because of a syntax error in this line
https://github.com/neuronets/kwyk/blob/fb12cb6324b7bfc7ed3dc385ca43ee3202d02fe8/Dockerfile.gpu#L37
@kaczmarj any idea what is wrong?

**Comment by kaczmarj** [comment]
@Hoda1394 - looks like the `get-pip.py` script requires python 3.6+, but this image uses python 3.5.

one solution is to replace the url with https://bootstrap.pypa.io/3.5/get-pip.py.

another solution is to use `tensorflow/tensorflow:1.12.3-py3` and `tensorflow/tensorflow:1.12.3-gpu-py3` as base images. if we used the tensorflow base, we would cut out a lot of stuff in our docker images. the one potential downside would be a larger image size.

**Comment by Hoda1394** [comment]
@kaczmarj - used the quick fix for images, now they work as expected and ready to be merged.

**Pull request merged**
